export { getDashboardSummary, getRevenueByMonth, getPipelineHealthByStage, getWinLossStats } from "./analytics.queries"
export { createActivity, deleteActivity, getActivitiesByCompany, getActivitiesByContact, getActivitiesByDeal, getRecentActivitiesByOrg } from "./activities.queries"
export {createWorkflow,deleteWorkflow,getActiveWorkflowsByOrg,getWorkflowById,getWorkflowsByOrg,incrementWorkflowRunCount,toggleWorkflow,updateWorkflow } from "./automation.queries"
export { createCompany, getCompanyById, getCompanyCount, getCompaniesByOrg, softDeleteCompany, searchCompanies, updateCompany } from "./companies.queries"
export { createContact, getContactCount, getContactById, getContactsByCompany, getContactsByOrg, searchContacts, softDeleteContact, updateContact, updateContactLastInteraction } from "./contacts.queries"
export { createDeal, getDealById, getDealsByCompany, getDealsByOrg, softDeleteDeal, updateDeal, getDealsByOwner, getDealStats, getDealsByPipeline, getDealsByStage, updateDealStage } from "./deals.queries"
export {createDocument, getDocumentById, getDocumentsByCompany, getDocumentsByDeal,getDocumentsByOrg,searchDocuments,softDeleteDocument,updateDocument} from "./documents.queries"
export { createNotification, getNotificationsByUser, getUnreadNotifications, markAllNotificationsRead, markNotificationRead } from "./notifications.queries"
export { createTask, getOverdueTasks, getTaskById, getTasksByAssignee, getTasksByCompany, getTasksByContact, getTasksByDeal, getTasksByOrg, softDeleteTask, updateTask } from "./tasks.queries"
export { createPipeline, createPipelineStage, deletePipeline, deletePipelineStage, getDefaultPipeline, getPipelineById, getPipelineWithStages, getPipelinesByOrg, getStageById, getStagesByPipeline, updatePipeline, updatePipelineStage } from "./pipelines.queries"
export {createAuditLog,getAuditLogsByOrg, } from "./audit.queries"
